### ISSUE TITLE
Solve many

### ISSUE THREAD

**Issue by albe2669** [albn-itu/algo2-red-scare#6]
# Description
Return the maximum number of red vertices on any path from
$s$ to $t$. To be precise, let $P$ be the set of $s$, $t$-paths and let $r(p)$ denote
the number of red vertices on a path $p$. Return $max { r(p): p \in P }$.
If no path from s to t exists, return ‘-1’. In Gex, the answer is ‘2’
(because of the path 0, 5, 6, 7, 3.)

# Tasks

- [x] #13
- [ ] Copy and paste our solution from BAPS

**Comment by arnenator** [comment]
Currently, I am exploring different solutions. These are some of my initial ideas:
- A solution that would prioritise edges that goes to a red vertex, by putting weights.
- A solution that uses DFS and can memorize the different max red paths
